name: Conventional Commits

on:
    pull_request:
        branches: [master]

jobs:
    build:
        name: Conventional Commits
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Check commit message
              uses: webiny/action-conventional-commits@v1.1.0
