name: Publish Package to npmjs

on:
    release:
        types: [created]

permissions:
  id-token: write
  contents: read

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Setup node
              uses: actions/setup-node@v4
              with:
                  node-version: '24.x'
                  registry-url: 'https://registry.npmjs.org'

            - name: Enable corepack
              run: corepack enable

            - name: Install dependencies
              run: yarn

            - name: Build monorepo
              run: yarn build

            - name: Make executable
              run: yarn make-executable

            - name: Publish packages
              run: npm publish
